app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  title: Bando Backstage
  baseUrl: https://${HEROKU_APP_NAME}.herokuapp.com

  organization:
    name: Bandokal
backend:
  baseUrl: https://${HEROKU_APP_NAME}.herokuapp.com
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: 
    port: 
      $env: PORT

  csp:
    connect-src: ["'self'", 'http:', 'https:']

  database:
    client: pg
    connection:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT}
      user: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    
proxy:
  /xkcd-proxy : https://xkcd.com/
  /substack : https://jasonbandy.substack.com/feed

catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/components/artist-lookup-component.yaml

    # Local example template
    - type: file
      target: ./templates/funraiser-website//template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
