version: '3'
services:
  backstage:
    image: bando-backstage
    environment:
      # This value must match the name of the postgres configuration block.
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: 1Qaws-plok
    ports:
      - '7007:7007'

  db:
    image: postgres
    restart: always
    environment:
    # NOT RECOMMENDED for a production environment. Trusts all incomming
      # connections.
      POSTGRES_HOST_AUTH_METHOD: trust